apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 2
    defaultRequest:
      memory: 256Mi
      cpu: 200m
    type: Container

limit,request设置后，pod中如果有设置会更新。	

	
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max-demo-lr
spec:
  limits:
  - max:
      memory: 1Gi
    min:
      memory: 500Mi
    type: Container
	
max，min。pod设置的请求不能超过范围，否则创建失败，pod若不设置。则request和limit都为1G